#!/bin/sh

### BEGIN INIT INFO
# Provides:        ATEN-EPICS
# Required-Start:  $network $remote_fs $syslog ntp
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop: 
# Short-Description: Start EPICS IOC for ATEN PDUs
### END INIT INFO

PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin

dev_eth0=`/sbin/ifconfig eth0 | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'`

case "$1" in
  start)
    echo -n "Starting ATEN-EPICS"
    export EPICS_HOST_ARCH=linux-x86_64
    export LD_LIBRARY_PATH=/opt/epics/base/lib/linux-x86_64

    export EPICS_CAS_INTF_ADDR_LIST=$dev_eth0
    cd /opt/ATEN-EPICS/iocBoot/iocATEN-EPICS
    screen -d -m -S ioc /opt/ATEN-EPICS/bin/linux-x86_64/ATEN-EPICS st.cmd 

    echo "."
    ;;
  stop)
    echo -n "Stopping ATEN-EPICS"
    kill -9 `/bin/pidof /opt/ATEN-EPICS/bin/linux-x86_64/ATEN-EPICS`
    unset EPICS_HOST_ARCH
    echo "."
    ;;
  force-reload|restart)
    sh $0 stop
    sh $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/ATEN-EPICS {start|stop|restart|force-reload}"
    exit 1
    ;;
esac
